services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: openmsp:latest
    container_name: ${CONTAINER_NAME:-openmsp_container}
    restart: always
    ports:
      - "${HOST_PORT:-8000}:8000"
    volumes:
      - sqlite_data:/app/db_data

volumes:
  sqlite_data:
    name: ${SQLITE_VOLUME_NAME:-openmsp_sqlite_data}
